# Generated by Django 4.0.4 on 2022-05-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botones', models.CharField(choices=[('Cero', '0'), ('Ocho', '8'), ('Doce', '12')], max_length=100)),
                ('piel_aro', models.CharField(choices=[('Cuero', 'Cuero'), ('Alcántara', 'Alcántara'), ('Plástico', 'Plástico'), ('Goma', 'Goma')], max_length=100)),
                ('tipo_volante', models.CharField(default='Formula 1 Actual', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('estado', models.CharField(choices=[('P', 'En Produccion'), ('E', 'Para Enviar')], default='P', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFormula1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botones', models.CharField(choices=[('8', '8'), ('15', '15')], max_length=100)),
                ('numero_levas', models.CharField(choices=[('Dos', '2'), ('Tres', '3'), ('Cuatro', '4')], max_length=20)),
                ('material_levas', models.CharField(choices=[('Plastico', 'Plástico'), ('Metal', 'Metal')], max_length=100)),
                ('display', models.BooleanField(default=False)),
                ('tipo_volante', models.CharField(default='Formula 1 Actual', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('estado', models.CharField(choices=[('P', 'En Produccion'), ('E', 'Para Enviar')], default='P', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTurismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botones', models.CharField(choices=[('Cinco', '5'), ('Diez', '10'), ('Quince', '15')], max_length=100)),
                ('numero_levas', models.CharField(choices=[('Cero', '0'), ('Dos', '2')], max_length=20)),
                ('material_levas', models.CharField(choices=[('Plastico', 'Plástico'), ('Metal', 'Metal')], max_length=100)),
                ('display', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('estado', models.CharField(choices=[('P', 'En Produccion'), ('E', 'Para Enviar')], default='P', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Volante_Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_breve', models.TextField(default='En proceso', max_length=300)),
                ('caracteristicas', models.TextField(default='En proceso', max_length=300)),
                ('descripcion_larga', models.TextField(max_length=900, null=True)),
                ('imagen', models.ImageField(blank=True, default='error404.png', upload_to='')),
                ('precio', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Error', max_length=50)),
                ('comprador', models.CharField(default='usuario no encontrado', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('estado', models.CharField(choices=[('P', 'En Produccion'), ('E', 'Para Enviar')], default='P', max_length=50)),
                ('dias_finalizar', models.CharField(default=30, max_length=3, null=True)),
                ('refCamion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipocamion')),
                ('refF1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoformula1')),
                ('refTienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volante_tienda')),
                ('refTurismo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoturismo')),
            ],
            options={
                'permissions': (('is_admin', 'is_admin'),),
            },
        ),
    ]
