# Generated by Django 4.0.4 on 2022-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoturismo',
            name='botones',
            field=models.CharField(choices=[('Ocho', '8'), ('Diez', '10')], max_length=100),
        ),
    ]
