# Generated by Django 4.0.4 on 2022-06-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Tarjeta de Crétido', 'Tarjeta de Crétido'), ('Contrarrembolso', 'Contrarrembolso')], max_length=50, null=True)),
                ('num_tarjeta', models.CharField(max_length=12, null=True)),
                ('caducidad', models.CharField(max_length=6, null=True)),
                ('cod_seguridad', models.IntegerField(max_length=3, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('ciudad', models.CharField(max_length=100, null=True)),
                ('provincia', models.CharField(max_length=100, null=True)),
                ('refPedido', models.ForeignKey(default=404, on_delete=django.db.models.deletion.CASCADE, to='app.pedidos')),
            ],
        ),
    ]
