# Generated by Django 4.0.4 on 2022-05-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tipoturismo_botones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoturismo',
            name='botones',
            field=models.CharField(choices=[('Ocho', '8'), ('Catorce', '14')], max_length=100),
        ),
    ]
