# Generated by Django 4.0.4 on 2022-06-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
