# Generated by Django 4.0.4 on 2022-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tipoturismo_botones'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocamion',
            name='intermitentes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipocamion',
            name='luces',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tipocamion',
            name='piel_aro',
            field=models.CharField(choices=[('Cuero', 'Cuero'), ('Alcántara', 'Alcántara'), ('Goma', 'Goma')], max_length=100),
        ),
    ]
