# Generated by Django 4.0.4 on 2022-05-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tipocamion_intermitentes_tipocamion_luces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocamion',
            name='botones',
            field=models.CharField(choices=[('Cero', '0'), ('Cuatro', '4')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tipocamion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipoformula1',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipoturismo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
        ),
    ]
