# Generated by Django 4.0.4 on 2022-06-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pedidos_refcamion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='refF1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoformula1', unique=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='refTurismo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipoturismo', unique=True),
        ),
    ]
