# Generated by Django 4.0.4 on 2022-06-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_usuariodatos_piso_alter_tipocamion_botones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volante_tienda',
            name='caracteristicas',
        ),
        migrations.AlterField(
            model_name='tipocamion',
            name='piel_aro',
            field=models.CharField(choices=[('Cuero', 'Cuero [+200€]'), ('Alcántara', 'Alcántara [+150€]'), ('Goma', 'Goma [+100€]')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoformula1',
            name='botones',
            field=models.CharField(choices=[('8', '8 [+50€]'), ('15', '15 [+100€]')], max_length=100),
        ),
    ]
