# Generated by Django 4.0.4 on 2022-06-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_volante_tienda_caracteristicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodatos',
            name='codigo_seguridad',
        ),
        migrations.RemoveField(
            model_name='usuariodatos',
            name='fecha_caducidad',
        ),
        migrations.RemoveField(
            model_name='usuariodatos',
            name='num_tarjeta',
        ),
        migrations.RemoveField(
            model_name='usuariodatos',
            name='tarjeta_credito',
        ),
    ]
