# Generated by Django 4.0.4 on 2022-06-17 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_remove_usuariodatos_codigo_seguridad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_credito', models.CharField(choices=[('MasterCard', 'Mastercard'), ('VISA', 'VISA')], default='Sin Pago', max_length=100)),
                ('num_tarjeta', models.CharField(default='Sin Tarjeta', max_length=100)),
                ('fecha_caducidad', models.CharField(default='Sin Fecha', max_length=100)),
                ('codigo_seguridad', models.CharField(default='Sin Codigo', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuariodatos',
            name='metodo_pago',
            field=models.ManyToManyField(max_length=100, null=True, to='app.tarjetacredito'),
        ),
    ]
