# Generated by Django 4.0.4 on 2022-06-17 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_tarjetacredito_usuariodatos_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='codigo_seguridad',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='fecha_caducidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='num_tarjeta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='tarjeta_credito',
            field=models.CharField(choices=[('MasterCard', 'Mastercard'), ('VISA', 'VISA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
