# Generated by Django 4.0.4 on 2022-06-17 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_tarjetacredito_codigo_seguridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
