# Generated by Django 4.0.4 on 2022-06-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_tarjetacredito_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='tarjeta_credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tarjetacredito'),
        ),
    ]
