# Generated by Django 4.0.4 on 2022-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pedidos_tarjeta_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='C/', max_length=100)),
                ('puerta', models.CharField(default='Puerta no introducida', max_length=100)),
                ('piso', models.CharField(max_length=10, null=True)),
                ('ciudad', models.CharField(default='Ciudad no introducida', max_length=100)),
                ('provincia', models.CharField(default='Provincia no introducida', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariodatos',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='usuariodatos',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuariodatos',
            name='piso',
        ),
        migrations.RemoveField(
            model_name='usuariodatos',
            name='provincia',
        ),
    ]
