# Generated by Django 4.0.4 on 2022-06-18 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_direccion_remove_usuariodatos_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuariodatos',
            name='direccion',
            field=models.ManyToManyField(max_length=100, null=True, to='app.direccion'),
        ),
    ]
