# Generated by Django 4.0.4 on 2022-06-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_direccion_user_usuariodatos_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.direccion'),
        ),
    ]
