# Generated by Django 4.0.4 on 2022-06-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_pedidos_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
