# Generated by Django 4.0.4 on 2022-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_direccion_piso'),
    ]

    operations = [
        migrations.AddField(
            model_name='volante_tienda',
            name='año',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='tarjetacredito',
            name='num_tarjeta',
            field=models.CharField(max_length=16),
        ),
    ]
