# Generated by Django 4.0.4 on 2022-06-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_volante_tienda_año_alter_tarjetacredito_num_tarjeta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volante_tienda',
            old_name='descripcion_larga',
            new_name='info_coche',
        ),
    ]
