# Generated by Django 4.0.4 on 2022-06-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_descripcion_larga_volante_tienda_info_coche'),
    ]

    operations = [
        migrations.AddField(
            model_name='volante_tienda',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
