# Generated by Django 4.0.4 on 2022-06-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_usuariodatos_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodatos',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuariodatos',
            name='metodo_pago',
        ),
    ]
