# Generated by Django 4.0.4 on 2022-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_usuariodatos_direccion_usuariodatos_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoturismo',
            name='material_levas',
            field=models.CharField(blank=True, choices=[('Plastico', 'Plástico [+0€]'), ('Metal', 'Metal [+50€]')], max_length=100, null=True),
        ),
    ]
